### ISSUE TITLE
CountDownTimer.ended method

### ISSUE THREAD

**Issue by landochan** [IrvKalb/pyghelpers#2]
I use ended method in my code to add score by 1 each second like this

`oScoreCountDownTimer = pyghelpers.CountDownTimer(1, True)`
`oScoreCountDownTimer.start()`
`while True:`
`    if oScoreCountDownTimer.ended():`
`        oScoreCountDownTimer.start()`
`        score += 1`

when I found out that this did not work.
The reason it did not work is because getTime functions are not executed, so that self.reachedZero is not updated. 

The solution now would be to call getTime before each if statement
or change the if statement to

`if oScoreCountDownTimer.getTime() == 0:`

The latter one is more effective but with this, ended method does not have any purpose to exist. I hope the ended method could work without getTime since it is less confusing and easier to use.
I believe there are many cases of use like my example above where I just want to know when the timer ends, without knowing what is the timer's time in every loop.

**Comment by IrvKalb** [comment]
Hello Lando,

Thank you for writing me about this issue.

I agree that having the CountDownTimer.ended() method have this additional functionality would be a good thing.  I've added it to the code - along with a few other enhancements (including a pause and resume for all three timers).  The reason it didn't work this way already was that I had only used it for a single game (the Slider Puzzle game) and I was always displaying the time in the window.

I'm attaching an updated experimental) version of pyghelpers.py, along with a small test program I built to make sure that it works as you expected.  Please try out this test, and if it works correctly, please try the updated pyghelpers.py with your program.  I've modified the ended() method to call the getTime() method and sets the internal variables properly ... encapsulation!

Please continue to try out the calls in both pygwidgets and pyghelpers and let me know if you find any other bugs or have any other enhancement requests.  It's great to know that there's someone out there who is using this code.  At some point, I would love to see the types of programs that you are building with these packages.  If you haven't already done so, I hope you'll get a chance to play around with the Scene Manager and build programs with multiple scenes.

Thanks again,

Irv

PS:  If you feel comfortable doing so, I would greatly appreciate it if you could write a quick review of the book on Amazon.com.
________________________________
From: Lando Chan ***@***.***>
Sent: Wednesday, February 15, 2023 5:05 PM
To: IrvKalb/pyghelpers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IrvKalb/pyghelpers] Opinion about CountDownTimer.ended method (Issue #2)


I use ended method in my code to add score by 1 each second like this

oScoreCountDownTimer = pyghelpers.CountDownTimer(1, True)
oScoreCountDownTimer.start()
while True:
if oScoreCountDownTimer.ended():
oScoreCountDownTimer.start()
score += 1

when I found out that this does not work.
Apparently self.reachedZero remains unchanged throughout the loop.
The reason it did not work is because getTime functions are not executed, so that self.reachedZero is not updated.

The solution now would be to call getTime before each if statement
or change the if statement to

if oScoreCountDownTimer.getTime() == 0:

The latter one is more effective and thus there seems to me that ended method does not have any purpose to exist. I hope the ended method could work without getTime since it is less confusing and easier to use.
I believe there are many cases of use like my example above where I just want to know when the timer ends, not what is the timer's time in every loop. So it will be less confusing to not have called the getTime function and I don't need to know why this method does not work by going through the implementation (as I learned OOP Encapsulation in your book, thanks!).
In the end, this is just my opinion.
I hope it could improve the already helping pyghelpers.

**Comment by landochan** [comment]
Sorry, I can't find any attachment either on github or email

**Comment by IrvKalb** [comment]
I'm having trouble with my email.  Let me try sending a zip file instead.

Please let me know if this gets through.

Irv
________________________________

**Comment by landochan** [comment]
No, I found no zip file

**Comment by IrvKalb** [comment]
Sorry, it probably has to do with the fact that you entered this as a problem through GitHub.  

So, I'm writing this on GitHub directly and I'll try to attach the file here.

If this still doesn't work, would you please send me your direct email address, and I'll send it that way.

Sorry for the confusion and delay.

Irv
[pyghelpersAndTest.zip](https://github.com/IrvKalb/pyghelpers/files/10763538/pyghelpersAndTest.zip)

**Comment by landochan** [comment]
It works.
Thank you very much.

**Comment by IrvKalb** [comment]
I'm happy to hear that it works.

If you are interested in other enhancements, please feel free to contact me directly at:  Irv at furrypants dot com

Irv
